// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwowmM_aKcOQ5Kkiptdyo6Kf4n_QT-QxQ',
    appId: '1:1005260421591:web:83092f51807faacb463392',
    messagingSenderId: '1005260421591',
    projectId: 'flutterbootstrap-d9c76',
    authDomain: 'flutterbootstrap-d9c76.firebaseapp.com',
    storageBucket: 'flutterbootstrap-d9c76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6AiyCn9IJFdg1IdAwI-IQHi-r_I2F3Z8',
    appId: '1:1005260421591:android:c912843334caf3c5463392',
    messagingSenderId: '1005260421591',
    projectId: 'flutterbootstrap-d9c76',
    storageBucket: 'flutterbootstrap-d9c76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsCQO2A567S1NAJ93QWjpbb1V2Rmyt3bM',
    appId: '1:1005260421591:ios:7cc1f2cc75e02ba3463392',
    messagingSenderId: '1005260421591',
    projectId: 'flutterbootstrap-d9c76',
    storageBucket: 'flutterbootstrap-d9c76.appspot.com',
    iosBundleId: 'com.example.flutterbootstrap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsCQO2A567S1NAJ93QWjpbb1V2Rmyt3bM',
    appId: '1:1005260421591:ios:7cc1f2cc75e02ba3463392',
    messagingSenderId: '1005260421591',
    projectId: 'flutterbootstrap-d9c76',
    storageBucket: 'flutterbootstrap-d9c76.appspot.com',
    iosBundleId: 'com.example.flutterbootstrap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwowmM_aKcOQ5Kkiptdyo6Kf4n_QT-QxQ',
    appId: '1:1005260421591:web:beed01332f4399c6463392',
    messagingSenderId: '1005260421591',
    projectId: 'flutterbootstrap-d9c76',
    authDomain: 'flutterbootstrap-d9c76.firebaseapp.com',
    storageBucket: 'flutterbootstrap-d9c76.appspot.com',
  );

}